### PR TITLE
Added Guns

### PR DESCRIPTION
**Pull request by Aegarain**
ASh12, Mk14 EBR, Super Shotgun, Gun racks, and f2000

### CODE REVIEW

**Comment by nrgill28** [comment]
Have you tested each of these mods and confirmed that installing them works? If not, it'd be great if you copied the branch url (`https://github.com/Aegarain/DeliCounter.Database/tree/patch-1`), pasted it into the "Mod Repository" setting box, then refreshed the repository on the home page and try installing each one and confirming they do install correctly.

e.g.
image

**Comment by Aegarain** [comment]
Ohh, that's how you test a repository. I'll get that done after dinner

**Comment by Aegarain** [comment]
All files were downloaded correctly.

**Comment by nrgill28** [comment]
Awesome, thanks!

**Pull request merged**
